version: 2.1

orbs:
  node-orb: heug/node@dev:0.0.2

jobs:
  build:
    executor:
      name: node-orb/node # put executor in the name
      tag: "6"
    steps:
      - checkout
      - node-orb/install_package_manager
          # yarn: true


workflows:
  build-test-deploy:
    jobs:
      - build