version: 2.1

orbs:
  node-orb:
    executors:
      node:
        parameters:
          tag:
            type: string
            default: "latest"
        docker:
          - image: circleci/node:<< parameters.tag >>
    jobs:
      helloworld:
        executor: node
        steps:
          - run: echo "hello world"
    commands:
      # install_npm:
      #   description: |
      # save_cache:
      #   description: |
      #     Save dependencies cache.

      #     This command will save a cache of node dependencies. It's recommended that
      #     this command be run before 

      #   parameters:
      #     deps-metadata:
      #       type: string
      #       default: package.json
      #   steps:
        
      with_cache:
        description: |
          Run a set of steps with node dependencies cached.

          This command will first restore a cache of node dependencies, if one was
          saved by a previous build. The provided `steps` will then be executed, and
          if successful, a fresh cache will be saved, if required.

          The contents of the `~/node_modules` directory is cached, which will substantially
          improve build times for projects with many dependencies. This directory can be changed
          with the `dir` parameter.

          The cache-key is generated from `package.json`. This file can be changed with the
          `deps-metadata` parameter.
        parameters:
          steps:
            type: steps
          dir:
            type: string
            default: ~/node_modules/
          deps-metadata:
            type: string
            default: package.json
        steps:
          - restore_cache:
              key: node-deps-{{ checksum << parameters.deps-metadata >> }}
          - steps: << parameters.steps >>
          - save_cache:
              key: node-deps-{{ checksum << parameters.deps-metadata >> }}
              paths:
                - << parameters.dir >>

# workflows:
#   build-test-deploy:
jobs:
  build:
    description: Let's give this a try
    executor: 
      name: node-orb/node
      tag: "6"
    steps:
      - checkout
      - npm init
      - npm i express
      - save_cache:
          keys: node-deps-{{ checksum "package.json" }}
          paths:
            - ~/node_modules