version: 2.1

orbs:
  node-orb:
    executors:
      node:
        parameters:
          tag:
            type: string
            default: latest
        docker:
          - image: circleci/node:<< parameters.tag >>
      mongo:
        parameters:
          tag:
            type: string
            default: latest
        docker:
          - image: circleci/mongo:<< parameters.tag >>
    jobs:
      helloworld:
        executor: node
        steps:
          - echo 'hello world'
       

workflows:
  build-test-deploy:
    jobs:
      - node-orb/helloworld